### ISSUE TITLE
Autopush: Too many open files error

### ISSUE THREAD

**Issue by jeffgorder** [benoitc/couchapp#5]
In version 8.1, when using Autopush, the following error occurs after the first save:

d54c48f88:05 Code Laptop$ couchapp autopush . coordel --update-delay 10
2011-05-12 07:03:44 [INFO] Starting to listen changes in '/Users/Laptop/Documents/Coordle/02 Products/Web/05 Code'
2011-05-12 07:04:00 [INFO] synchronize changes
2011-05-12 07:04:00 [INFO] unhandled exception in main loop:
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/couchapp/autopush/watcher.py", line 75, in run
  File "/Library/Python/2.6/site-packages/couchapp/autopush/handler.py", line 50, in maybe_update
  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 122, in push
  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 185, in doc
  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 298, in dir_to_fields
OSError: [Errno 24] Too many open files: '/Users/Laptop/Documents/Coordle/02 Products/Web/05 Code'

**Comment by benoitc** [comment]
On Thu, May 12, 2011 at 7:07 AM, jeffgorder
reply@reply.github.com
wrote:

> In version 8.1, when using Autopush, the following error occurs after the first save:
> 
> d54c48f88:05 Code Laptop$ couchapp autopush . coordel --update-delay 10
> 2011-05-12 07:03:44 [INFO] Starting to listen changes in '/Users/Laptop/Documents/Coordle/02 Products/Web/05 Code'
> 2011-05-12 07:04:00 [INFO] synchronize changes
> 2011-05-12 07:04:00 [INFO] unhandled exception in main loop:
> Traceback (most recent call last):
>  File "/Library/Python/2.6/site-packages/couchapp/autopush/watcher.py", line 75, in run
>  File "/Library/Python/2.6/site-packages/couchapp/autopush/handler.py", line 50, in maybe_update
>  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 122, in push
>  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 185, in doc
>  File "/Library/Python/2.6/site-packages/couchapp/localdoc.py", line 298, in dir_to_fields
> OSError: [Errno 24] Too many open files: '/Users/Laptop/Documents/Coordle/02 Products/Web/05 Code'
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/benoitc/couchapp/issues/5

How many files do you have in attachments ?

**Comment by benoitc** [comment]
can't reproduce with latest version. Feel free to repoen an issue if it still happen.

**Comment by barbalex** [comment]
I get the exact same error:
Alexander-Gabriels-MacBook-Pro:EvAB Alex$ couchapp autopush EvAB http://barbalex:dLhdMg12@barbalex.iriscouch.com/evab
2011-11-30 21:11:37 [INFO] Starting to listen changes in '/Users/Alex/EvAB/EvAB'
2011-11-30 21:11:51 [INFO] synchronize changes
2011-11-30 21:11:51 [INFO] unhandled exception in main loop:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/couchapp/autopush/watcher.py", line 75, in run
  File "/Library/Python/2.7/site-packages/couchapp/autopush/handler.py", line 53, in maybe_update
  File "/Library/Python/2.7/site-packages/couchapp/localdoc.py", line 122, in push
  File "/Library/Python/2.7/site-packages/couchapp/localdoc.py", line 185, in doc
  File "/Library/Python/2.7/site-packages/couchapp/localdoc.py", line 298, in dir_to_fields
OSError: [Errno 24] Too many open files: '/Users/Alex/EvAB/EvAB'

I'm using:
Couchapp 0.8.1
couchdb 1.1.1
OSX Lion

There are 9 html files in attachments

the error does not happen using push instead of autopush
